#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE="nzbget"
HOME="$(omv_config_get "/config/services/nzbget/folder")"

if [ ! $(ls -ld "$HOME" | awk '{print $3}') = "nzbget" ]; then
    chown -R nzbget:nzbget "${HOME}"
fi

