#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_NZBGET_USER="nzbget"
OMV_NZBGET_GROUP="nzbget"
ControlUsername=""
ControlPassword=""

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "${2}" ]; then
            systemctl stop nzbget.service >/dev/null || true
            systemctl disable nzbget.service >/dev/null || true
        fi

        if ! getent group nzbget >/dev/null; then
            groupadd -r nzbget >/dev/null
        fi

        if ! getent passwd nzbget >/dev/null; then
            useradd -r -g nzbget -d /var/lib/nzbget -s /bin/false -c nzbget nzbget >/dev/null
        fi

        if [ ! -f "/usr/share/nzbget/nzbget" ]; then
            echo "Installing latest NZBGet stable version"
            cd /usr/share
            link=`wget -q -O - http://nzbget.net/info/nzbget-version-linux.json | sed -n "s/^.*stable-download.*: \"\(.*\)\".*/\1/p"`
            if [ -z $link ]; then
                echo "No stable link found, installing latest NZBGet testing version"
                link=`wget -q -O - http://nzbget.net/info/nzbget-version-linux.json | sed -n "s/^.*testing-download.*: \"\(.*\)\".*/\1/p"`
            fi
            echo "Please wait, downloading files....."
            wget ${link} -O /usr/share/nzbget-bin-linux.run > /dev/null 2>&1
            chmod +x /usr/share/nzbget-bin-linux.run
            ./nzbget-bin-linux.run
            rm -Rf /usr/share/nzbget-bin-linux.run
            # Make changes to the default conf file.
            if [ -f "/opt/nzbget/nzbget.conf" ]; then
                mv /opt/nzbget/nzbget.conf /usr/share/nzbget/nzbget.conf.backup
                rm -Rf /opt/nzbget
                ControlUsername=`sed -n '/ControlUsername=/ s///p' /usr/share/nzbget/nzbget.conf.backup | uniq`
                ControlPassword=`sed -n '/ControlPassword=/ s///p' /usr/share/nzbget/nzbget.conf.backup | uniq`
            fi

            if [ -z $ControlUsername ]; then
                ControlUsername=openmediavault
            fi

            if [ -z $ControlPassword ]; then
                ControlPassword=openmediavault
            fi
            # Anything else?
            sed -i 's/ControlUsername.*/ControlUsername='$ControlUsername'/g' /usr/share/nzbget/nzbget.conf
            sed -i 's/ControlPassword.*/ControlPassword='$ControlPassword'/g' /usr/share/nzbget/nzbget.conf
            sed -i 's/DaemonUsername.*/DaemonUsername=nzbget/g' /usr/share/nzbget/nzbget.conf
            sed -i 's/UMask.*/UMask=0000/g' /usr/share/nzbget/nzbget.conf
        fi

        SERVICE_XPATH_NAME="nzbget"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if dpkg --compare-versions "${2}" lt-nl "3.1"; then
            if omv_config_exists "${SERVICE_XPATH}"; then
                ENABLE="$(omv_config_get "${SERVICE_XPATH}/enable")"
                SHOWTAB="$(omv_config_get "${SERVICE_XPATH}/showtab")"
                DREF="$(omv_config_get "${SERVICE_XPATH}/download.sharedfolderref")"
                MDIR="$(omv_config_get "${SERVICE_XPATH}/main-dir")"
                PORT="$(omv_config_get "${SERVICE_XPATH}/port")"
            else
                ENABLE="0"
                SHOWTAB="0"
                DREF=""
                MDIR=""
                PORT="6789"
            fi

            omv_config_delete "${SERVICE_XPATH}"

            if ! omv_config_exists "${SERVICE_XPATH}"; then
                omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
                omv_config_add_element "${SERVICE_XPATH}" "enable" $ENABLE
                omv_config_add_element "${SERVICE_XPATH}" "showtab" $SHOWTAB
                omv_config_add_element "${SERVICE_XPATH}" "mntentref" $DREF
                omv_config_add_element "${SERVICE_XPATH}" "main-dir" $MDIR
                omv_config_add_element "${SERVICE_XPATH}" "port" $PORT
            fi
        fi

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            echo "Initial configuration."
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "showtab" "0"
            omv_config_add_element "${SERVICE_XPATH}" "mntentref" ""
            omv_config_add_element "${SERVICE_XPATH}" "main-dir" ""
            omv_config_add_element "${SERVICE_XPATH}" "port" "6789"
        fi

        chown -R $OMV_NZBGET_USER:$OMV_NZBGET_GROUP /usr/share/nzbget
        chmod -R 775 /usr/share/nzbget

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

