#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        if [ -d /etc/init.d/nzbget ]; then
            /ect/init.d/nzbget stop
        fi

        if [ -d /opt/nzbget ]; then
            rm -Rf /opt/nzbget
        fi

        if [ -d /usr/share/nzbget ]; then
            rm -Rf /usr/share/nzbget
        fi

        omv_config_delete "//services/nzbget"

        if getent passwd nzbget >/dev/null 2>&1; then
            userdel -rf nzbget
        fi

        if [ ! -d /opt ]; then
            mkdir /opt
            chmod 775 /opt
        fi

        if [ ! -d /var/opt ]; then
            mkdir /var/opt
            chmod 775 /opt
        fi
        ;;

        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

        *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
