#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        if [ ! -z "$(pidof nzbget)" ]; then
            pkill -9 -u `id -u nzbget` >/dev/null >&2
        fi

        if [ -d "/usr/share/nzbget" ]; then
            rm -Rf /usr/share/nzbget
        fi

        omv_config_delete "//services/nzbget"

        if getent passwd nzbget >/dev/null 2>&1; then
            userdel -rf nzbget >/dev/null 2>&1
        fi

        ;;

        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

        *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
