#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_NZBGET_USER="nzbget"
OMV_NZBGET_GROUP="users"
OMV_NZBGET_VERSION="14.1"

case "$1" in
    configure)
        if ! getent passwd nzbget >/dev/null 2>&1; then
            echo "Adding nzbget user..."
            adduser --quiet \
                    --system \
                    --ingroup $OMV_NZBGET_GROUP \
                    --disabled-password \
                    $OMV_NZBGET_USER
            insserv -d nzbget
        else
            echo "nzbget user already exists."
        fi

        if [ ! -f "/usr/share/nzbget/nzbget.conf" ]; then
            mv /usr/share/nzbget/nzbget.conf.new /usr/share/nzbget/nzbget.conf
        else
            rm -f /usr/share/nzbget/nzbget.conf.new
        fi

        if [ ! -f "/home/nzbget/downloads" ]; then
            mkdir -p /home/nzbget/downloads
        fi

        if [ ! -f "/opt/nzbget/nzbget" ]; then
            echo "installing nzbget binary file"
            cd /opt/nzbget
            arch=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/')
            if [ $arch -eq 32 ]; then
                echo "Installing binary file for a 32 bit systems"
                tar -zxf nzbget.tar.gz nzbget_i386
            elif [ $arch -eq 64 ]; then
                echo "Installing binary file for a 64 bit systems"
                tar -zxf nzbget.tar.gz nzbget_amd64
            else
                echo "Installing binary file for a arm type systems"
                tar -zxf nzbget.tar.gz nzbget_arm
            fi
            mv nzbget_* nzbget
        else
            # Get current version.
            OMV_INSTALLED_VERSION=$(/opt/nzbget/nzbget -v | cut -d ' ' -f 3)
            if [ "$OMV_NZBGET_VERSION" \> "$OMV_INSTALLED_VERSION" ]; then
                echo "Installing Updated Version."
                cd /opt/nzbget
                arch=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/')
                if [ $arch -eq 32 ]; then
                    echo "Installing binary file for a 32 bit systems"
                    tar -zxf nzbget.tar.gz nzbget_i386
                elif [ $arch -eq 64 ]; then
                    echo "Installing binary file for a 64 bit systems"
                    tar -zxf nzbget.tar.gz nzbget_amd64
                else
                    echo "Installing binary file for a arm type systems"
                    tar -zxf nzbget.tar.gz nzbget_arm
                fi
                rm nzbget
                mv nzbget_* nzbget
            fi
        fi

        if [ -f "/opt/nzbget/nzbget.tar.gz" ]; then
            rm -f /opt/nzbget/nzbget.tar.gz
        fi

        if ! omv_config_exists "/config/services/nzbget"; then
            echo "Initial configuration."
            object="<enable>0</enable>"
            object="${object}<showtab>0</showtab>"
            omv_config_add_element "/config/services" "nzbget" "${object}" true
        fi

        chown -R nzbget:users /opt/nzbget /home/nzbget/downloads /usr/share/nzbget
        chown -R nzbget:users /etc/init.d/nzbget
        chmod -R 775 /opt/nzbget /usr/share/nzbget /home/nzbget/downloads

        omv_install_fixperms

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
